const DEFAULT_USER_PASSWORD = process.env.DEFAULT_USER_PASSWORD || 'IBBI2026';
const SEED_MASTER_PASSWORD = process.env.SEED_MASTER_PASSWORD;

module.exports = { DEFAULT_USER_PASSWORD, SEED_MASTER_PASSWORD };
